/**
 * Type-safe route definitions for Expo Router.
 * These extend the typed routes generated by Expo.
 */

export type CRMDetailParams = {
  id: string;
  type: 'lead' | 'customer' | 'deal' | 'contact';
};

export type EquipmentDetailParams = {
  id: string;
};
