-- AUDIT-010: one live permission_cache row per (user, organizational context, tenant).
--
-- WHY THE DELETE COMES FIRST: setCachedPermissions has always done a plain INSERT, so
-- every cache miss / expiry / invalidation left ANOTHER row for the same key. This
-- table therefore almost certainly CONTAINS DUPLICATES right now, and CREATE UNIQUE
-- INDEX would simply fail against them ("could not create unique index ... key is
-- duplicated"). The rows must go before the constraint can exist.
--
-- WHY A BLANK DELETE IS SAFE HERE (rather than a keep-the-newest dedupe): permission_cache
-- is a pure CACHE — every row is derived data, regenerated by
-- PermissionCacheService.setCachedPermissions on the next request that misses. Emptying
-- it costs one permission recomputation per active user and cannot lose information.
-- That is strictly simpler, and safer, than a DISTINCT ON dedupe that has to pick a
-- winner. The L1 in-memory cache is unaffected.
--
-- Hand-authored (drizzle-kit generate is unusable in this repo — its snapshots stop at
-- 0009 while migrations run past 0028; see the AUDIT-009 notes). Journalled as idx 13 so
-- `npm run db:migrate` actually applies it.

DELETE FROM "permission_cache";--> statement-breakpoint

-- The upsert in setCachedPermissions targets exactly this triple. ON CONFLICT requires
-- a UNIQUE constraint/index; the pre-existing idx_permission_cache_user_context is a
-- plain index and cannot serve it (and omits tenant_id).
CREATE UNIQUE INDEX IF NOT EXISTS "permission_cache_user_context_tenant_uniq" ON "permission_cache" USING btree ("user_id","organizational_context","tenant_id");
