ALTER TABLE "auto_supply_orders" ALTER COLUMN "equipment_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "auto_supply_orders" ALTER COLUMN "supplier_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "supply_monitoring" ALTER COLUMN "equipment_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "supply_replenishment_rules" ALTER COLUMN "preferred_supplier_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "supply_usage_history" ALTER COLUMN "equipment_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "contract_renewal_tracking" ALTER COLUMN "contract_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "contract_renewal_tracking" ALTER COLUMN "customer_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "contract_renewal_tracking" ALTER COLUMN "assigned_sales_rep_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "document_field_mappings" ALTER COLUMN "created_by" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "document_notifications" ALTER COLUMN "recipient_user_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "document_notifications" ALTER COLUMN "workflow_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "document_notifications" ALTER COLUMN "task_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "document_templates" ALTER COLUMN "created_by" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "document_uploads" ALTER COLUMN "target_entity_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "document_uploads" ALTER COLUMN "workflow_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "document_uploads" ALTER COLUMN "task_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "document_uploads" ALTER COLUMN "reviewed_by" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "document_uploads" ALTER COLUMN "uploaded_by" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "document_workflow_actions" ALTER COLUMN "workflow_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "document_workflow_actions" ALTER COLUMN "created_by" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "generated_documents" ALTER COLUMN "workflow_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "generated_documents" ALTER COLUMN "task_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "generated_documents" ALTER COLUMN "business_record_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "generated_documents" ALTER COLUMN "quote_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "generated_documents" ALTER COLUMN "deal_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "generated_documents" ALTER COLUMN "service_call_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "generated_documents" ALTER COLUMN "generated_by" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "renewal_communication_log" ALTER COLUMN "customer_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "renewal_communication_log" ALTER COLUMN "sent_by_user_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "renewal_proposals" ALTER COLUMN "contract_id" SET DATA TYPE varchar;--> statement-breakpoint
ALTER TABLE "renewal_proposals" ALTER COLUMN "customer_id" SET DATA TYPE varchar;