-- WF-L-04: receiving creates equipment rows, so equipment has to know where it
-- came from - and a unit in the warehouse has to be allowed to belong to nobody.
--
-- POST /purchase-orders/:id/receive moved inventory counts and nothing else,
-- POST /equipment had no caller in any client tree, and the Add Equipment dialog
-- on the customer page rendered "Equipment registration form would go here". A
-- purchase order could be fully received and no equipment row would exist for
-- meter billing, service or the lifecycle.
--
-- DROP NOT NULL on customer_id is the part that makes the feature possible at
-- all. A unit received against a stock purchase order - the kind WF-P-03 says
-- carries no contract, deal or customer - has no customer until it is delivered.
-- Nothing reads the column expecting a value: every customer surface filters ON
-- customer_id, so an unassigned unit does not appear on anyone's tab, which is
-- the right answer for a machine nobody has bought yet.
--
-- Generated by npm run db:generate (three statements, nothing else) and then
-- given IF NOT EXISTS so it is safe to re-run.
ALTER TABLE "equipment" ALTER COLUMN "customer_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "purchase_order_id" varchar;--> statement-breakpoint
ALTER TABLE "equipment" ADD COLUMN IF NOT EXISTS "purchase_order_item_id" varchar;--> statement-breakpoint

-- The lookups this story creates: "what did we receive against this PO".
CREATE INDEX IF NOT EXISTS equipment_purchase_order_idx ON equipment (tenant_id, purchase_order_id);
