-- WF-P-08: a task belongs to the record it is about.
--
-- tasks.customer_id has existed since migration 0002 and the tasks handler's
-- mapper never read or wrote it, so a task could not be attached to the account
-- it concerned - and there was no deal or handoff link at all. Every task in the
-- system was a floating to-do with an assignee and no subject, which is why
-- nothing on a record page could list its work.
--
-- Both nullable: a personal to-do belongs to nothing, and that is a real task
-- rather than an incomplete one. No foreign keys, for the reason 0074 records:
-- adding a constraint from a side that a soft delete or a tenant purge walks
-- first is how a migration comes to fail on one database and not another.
--
-- Generated by npm run db:generate (two statements, nothing else) and given
-- IF NOT EXISTS so it is safe to re-run.
ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "deal_id" varchar;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "handoff_id" varchar;--> statement-breakpoint

-- The lookups this story creates: "what work is outstanding on this record".
CREATE INDEX IF NOT EXISTS tasks_tenant_customer_idx ON tasks (tenant_id, customer_id);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS tasks_tenant_deal_idx ON tasks (tenant_id, deal_id);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS tasks_tenant_handoff_idx ON tasks (tenant_id, handoff_id);
