// Build a single, zero-dependency Windows executable (printyx-client.exe) by
// wrapping the esbuild bundle in a Node Single Executable Application (SEA).
//
//   dist/printyx-client.cjs  --(node --experimental-sea-config)-->  sea blob
//   win-x64 node.exe         --(postject inject blob)------------>  printyx-client.exe
//
// The result needs NOTHING on the target — Node is embedded. This is the
// "IT can't install anything" artifact. It's OPT-IN (not in the default
// build/Docker pipeline) and EXPERIMENTAL: auto-update is disabled for .exe
// installs (a SEA can't easily self-replace), and the produced binary is
// unsigned (SmartScreen may warn until you sign it with your cert).
//
// Cross-platform: the SEA blob is generated by THIS node, and we download a
// win-x64 node.exe of the SAME version to inject into. Run on any OS.
import { execFileSync } from 'node:child_process';
import { existsSync, copyFileSync, readFileSync, writeFileSync, mkdirSync, createWriteStream } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import https from 'node:https';
import { inject } from 'postject';

const root = dirname(fileURLToPath(import.meta.url));
const dist = join(root, 'dist');
const bundle = join(dist, 'printyx-client.cjs');
const blob = join(dist, 'sea-prep.blob');
const exeOut = join(dist, 'printyx-client.exe');
const nodeVersion = process.version; // e.g. v20.18.1
const SENTINEL = 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2';

function step(msg) {
  console.log(`\n==> ${msg}`);
}

function download(url, dest) {
  return new Promise((resolve, reject) => {
    const file = createWriteStream(dest);
    const get = (u) =>
      https
        .get(u, (res) => {
          if (res.statusCode && res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
            res.resume();
            return get(res.headers.location);
          }
          if (res.statusCode !== 200) {
            reject(new Error(`HTTP ${res.statusCode} for ${u}`));
            return;
          }
          res.pipe(file);
          file.on('finish', () => file.close(() => resolve()));
        })
        .on('error', reject);
    get(url);
  });
}

async function main() {
  if (!existsSync(dist)) mkdirSync(dist, { recursive: true });

  // 1. Ensure the esbuild bundle exists (it's the SEA "main").
  if (!existsSync(bundle)) {
    step('Bundle not found — running esbuild first');
    execFileSync(process.execPath, [join(root, 'esbuild.config.mjs')], { stdio: 'inherit' });
  }

  // 2. Generate the SEA blob from the bundle (platform-independent).
  step('Generating SEA blob (node --experimental-sea-config)');
  execFileSync(process.execPath, ['--experimental-sea-config', 'sea-config.json'], {
    cwd: root,
    stdio: 'inherit',
  });
  if (!existsSync(blob)) throw new Error('SEA blob was not produced');

  // 3. Acquire a win-x64 node.exe of the SAME version to host the blob.
  const cachedNode = join(dist, `node-win-x64-${nodeVersion}.exe`);
  if (!existsSync(cachedNode)) {
    const url = `https://nodejs.org/dist/${nodeVersion}/win-x64/node.exe`;
    step(`Downloading host runtime: ${url}`);
    await download(url, cachedNode);
  } else {
    step(`Using cached host runtime ${cachedNode}`);
  }

  // 4. Copy and inject the blob into the binary's resources.
  step('Injecting SEA blob into printyx-client.exe (postject)');
  copyFileSync(cachedNode, exeOut);
  await inject(exeOut, 'NODE_SEA_BLOB', readFileSync(blob), { sentinelFuse: SENTINEL });

  // 5. Manifest entry so the platform/installer know an exe is available.
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
  writeFileSync(
    join(dist, 'exe-manifest.json'),
    JSON.stringify(
      { name: pkg.name, version: pkg.version, runtime: nodeVersion, entry: 'printyx-client.exe', signed: false },
      null,
      2,
    ),
  );

  console.log(`\nBuilt ${exeOut} (embedded ${nodeVersion}, unsigned).`);
  console.log('NOTE: experimental + unsigned. Sign with signtool before wide distribution.');
}

main().catch((err) => {
  console.error('build-exe failed:', err.message);
  process.exit(1);
});
