/**
 * SEED DATA FOR DASHBOARD WIDGETS
 * Comprehensive widget library for all roles and departments
 */

import { db } from './db';
import { dashboardWidgets } from '@shared/schema-dashboard';
import { createModuleLogger } from './lib/logger';
const log = createModuleLogger('seed-dashboard-widgets');

export const dashboardWidgetDefinitions = [
  // ============================================================================
  // SERVICE DEPARTMENT WIDGETS
  // ============================================================================
  {
    key: 'service-open-tickets',
    name: 'Open Service Tickets',
    description: 'Number of unassigned and open service tickets',
    type: 'kpi',
    icon: 'AlertCircle',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'service.view_tickets',
    applicableRoles: ['service_manager', 'technician', 'service_admin'],
    applicableModules: ['Service'],
    defaultConfig: { metric: 'open_count', threshold: 5 },
    configurableFields: ['threshold', 'timeRange'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: true,
  },
  {
    key: 'service-in-progress',
    name: 'In Progress Tickets',
    description: 'Tickets currently being worked on by technicians',
    type: 'kpi',
    icon: 'Clock',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'service.view_tickets',
    applicableRoles: ['service_manager', 'technician', 'service_admin'],
    applicableModules: ['Service'],
    defaultConfig: { metric: 'in_progress_count' },
    configurableFields: ['timeRange'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: true,
  },
  {
    key: 'service-overdue',
    name: 'Overdue Tickets',
    description: 'Service tickets past their SLA deadline',
    type: 'kpi',
    icon: 'AlertTriangle',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'service.view_tickets',
    applicableRoles: ['service_manager', 'service_admin'],
    applicableModules: ['Service'],
    defaultConfig: { metric: 'overdue_count', severity: 'high' },
    configurableFields: ['timeRange'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: true,
  },
  {
    key: 'service-pending-customer',
    name: 'Pending Customer Response',
    description: 'Tickets waiting for customer action or response',
    type: 'kpi',
    icon: 'HelpCircle',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'service.view_tickets',
    applicableRoles: ['service_manager', 'service_admin'],
    applicableModules: ['Service'],
    defaultConfig: { metric: 'pending_customer_count' },
    configurableFields: ['timeRange'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: true,
  },
  {
    key: 'service-technician-utilization',
    name: 'Technician Utilization',
    description: 'Percentage of technicians actively assigned to tickets',
    type: 'chart',
    icon: 'Users',
    defaultWidth: 6,
    defaultHeight: 300,
    requiredPermission: 'service.view_technicians',
    applicableRoles: ['service_manager', 'service_admin'],
    applicableModules: ['Service'],
    defaultConfig: { chartType: 'bar', metric: 'utilization_percent' },
    configurableFields: ['timeRange', 'groupBy'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },
  {
    key: 'service-sla-compliance',
    name: 'SLA Compliance',
    description: 'Percentage of tickets completed within SLA',
    type: 'chart',
    icon: 'TrendingUp',
    defaultWidth: 6,
    defaultHeight: 300,
    requiredPermission: 'service.view_tickets',
    applicableRoles: ['service_manager', 'service_admin'],
    applicableModules: ['Service'],
    defaultConfig: { chartType: 'line', metric: 'sla_compliance_percent' },
    configurableFields: ['timeRange'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },
  {
    key: 'service-equipment-status',
    name: 'Equipment Status',
    description: 'Health status of monitored equipment',
    type: 'table',
    icon: 'Zap',
    defaultWidth: 12,
    defaultHeight: 400,
    requiredPermission: 'service.view_equipment',
    applicableRoles: ['service_manager', 'technician', 'service_admin'],
    applicableModules: ['Service', 'IoT'],
    defaultConfig: { columns: ['equipment_name', 'status', 'last_reading', 'alerts'] },
    configurableFields: ['columns', 'sortBy', 'filterBy'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: true,
  },
  {
    key: 'service-response-time',
    name: 'Avg Response Time',
    description: 'Average time to first response on tickets',
    type: 'kpi',
    icon: 'Zap',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'service.view_tickets',
    applicableRoles: ['service_manager', 'service_admin'],
    applicableModules: ['Service'],
    defaultConfig: { metric: 'avg_response_time_minutes' },
    configurableFields: ['timeRange'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },
  {
    key: 'service-ticket-aging',
    name: 'Ticket Aging',
    description: 'Distribution of tickets by age',
    type: 'chart',
    icon: 'Clock',
    defaultWidth: 6,
    defaultHeight: 300,
    requiredPermission: 'service.view_tickets',
    applicableRoles: ['service_manager', 'service_admin'],
    applicableModules: ['Service'],
    defaultConfig: { chartType: 'bar' },
    configurableFields: ['ageRanges'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },

  // ============================================================================
  // SALES/CRM WIDGETS
  // ============================================================================
  {
    key: 'crm-pipeline-value',
    name: 'Sales Pipeline Value',
    description: 'Total value of all opportunities in pipeline',
    type: 'kpi',
    icon: 'TrendingUp',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'crm.view_opportunities',
    applicableRoles: ['sales_manager', 'sales_rep', 'crm_admin'],
    applicableModules: ['CRM'],
    defaultConfig: { metric: 'total_pipeline_value' },
    configurableFields: ['timeRange', 'stageName'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: true,
  },
  {
    key: 'crm-deals-won',
    name: 'Deals Won',
    description: 'Number of deals closed this period',
    type: 'kpi',
    icon: 'Check',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'crm.view_opportunities',
    applicableRoles: ['sales_manager', 'sales_rep', 'crm_admin'],
    applicableModules: ['CRM'],
    defaultConfig: { metric: 'deals_won_count' },
    configurableFields: ['timeRange'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: true,
  },
  {
    key: 'crm-conversion-rate',
    name: 'Conversion Rate',
    description: 'Percentage of leads converted to customers',
    type: 'kpi',
    icon: 'Percent',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'crm.view_opportunities',
    applicableRoles: ['sales_manager', 'crm_admin'],
    applicableModules: ['CRM'],
    defaultConfig: { metric: 'conversion_rate_percent' },
    configurableFields: ['timeRange'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },
  {
    key: 'crm-leads-qualified',
    name: 'Qualified Leads',
    description: 'Leads that passed qualification criteria',
    type: 'kpi',
    icon: 'Star',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'crm.view_leads',
    applicableRoles: ['sales_manager', 'sales_rep', 'crm_admin'],
    applicableModules: ['CRM'],
    defaultConfig: { metric: 'qualified_leads_count' },
    configurableFields: ['timeRange', 'source'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: true,
  },
  {
    key: 'crm-pipeline-by-stage',
    name: 'Pipeline by Stage',
    description: 'Breakdown of opportunities by sales stage',
    type: 'chart',
    icon: 'Funnel',
    defaultWidth: 6,
    defaultHeight: 300,
    requiredPermission: 'crm.view_opportunities',
    applicableRoles: ['sales_manager', 'crm_admin'],
    applicableModules: ['CRM'],
    defaultConfig: { chartType: 'bar' },
    configurableFields: ['timeRange'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: true,
  },
  {
    key: 'crm-forecast',
    name: 'Sales Forecast',
    description: 'Predicted revenue based on pipeline',
    type: 'chart',
    icon: 'BarChart3',
    defaultWidth: 6,
    defaultHeight: 300,
    requiredPermission: 'crm.view_opportunities',
    applicableRoles: ['sales_manager', 'crm_admin'],
    applicableModules: ['CRM'],
    defaultConfig: { chartType: 'line', metric: 'forecast_revenue' },
    configurableFields: ['timeRange', 'confidenceLevel'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },
  {
    key: 'crm-rep-performance',
    name: 'Rep Performance',
    description: 'Sales metrics by representative',
    type: 'table',
    icon: 'Users',
    defaultWidth: 12,
    defaultHeight: 400,
    requiredPermission: 'crm.view_opportunities',
    applicableRoles: ['sales_manager', 'crm_admin'],
    applicableModules: ['CRM'],
    defaultConfig: { columns: ['rep_name', 'deals_won', 'pipeline_value', 'conversion_rate'] },
    configurableFields: ['columns', 'sortBy', 'timeRange'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: true,
  },

  // ============================================================================
  // BILLING & FINANCE WIDGETS
  // ============================================================================
  {
    key: 'billing-monthly-revenue',
    name: 'Monthly Revenue',
    description: 'Total revenue this month',
    type: 'kpi',
    icon: 'DollarSign',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'billing.view_invoices',
    applicableRoles: ['finance_manager', 'billing_admin', 'accountant'],
    applicableModules: ['Billing'],
    defaultConfig: { metric: 'monthly_revenue' },
    configurableFields: ['timeRange'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },
  {
    key: 'billing-outstanding-invoices',
    name: 'Outstanding Invoices',
    description: 'Total value of unpaid invoices',
    type: 'kpi',
    icon: 'AlertTriangle',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'billing.view_invoices',
    applicableRoles: ['finance_manager', 'billing_admin', 'accountant'],
    applicableModules: ['Billing'],
    defaultConfig: { metric: 'outstanding_amount' },
    configurableFields: ['daysOverdue'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: true,
  },
  {
    key: 'billing-collection-rate',
    name: 'Collection Rate',
    description: 'Percentage of invoices paid on time',
    type: 'kpi',
    icon: 'Check',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'billing.view_invoices',
    applicableRoles: ['finance_manager', 'billing_admin'],
    applicableModules: ['Billing'],
    defaultConfig: { metric: 'collection_rate_percent' },
    configurableFields: ['timeRange'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },
  {
    key: 'billing-recurring-revenue',
    name: 'Recurring Revenue',
    description: 'Monthly recurring revenue from contracts',
    type: 'kpi',
    icon: 'Repeat',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'billing.view_contracts',
    applicableRoles: ['finance_manager', 'billing_admin', 'accountant'],
    applicableModules: ['Billing'],
    defaultConfig: { metric: 'mrr_total' },
    configurableFields: ['contractType'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },
  {
    key: 'billing-revenue-trend',
    name: 'Revenue Trend',
    description: 'Revenue comparison over time',
    type: 'chart',
    icon: 'TrendingUp',
    defaultWidth: 6,
    defaultHeight: 300,
    requiredPermission: 'billing.view_invoices',
    applicableRoles: ['finance_manager', 'billing_admin'],
    applicableModules: ['Billing'],
    defaultConfig: { chartType: 'line' },
    configurableFields: ['timeRange', 'groupBy'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },
  {
    key: 'billing-aging-analysis',
    name: 'Aging Analysis',
    description: 'Invoices grouped by days overdue',
    type: 'chart',
    icon: 'Clock',
    defaultWidth: 6,
    defaultHeight: 300,
    requiredPermission: 'billing.view_invoices',
    applicableRoles: ['finance_manager', 'billing_admin'],
    applicableModules: ['Billing'],
    defaultConfig: { chartType: 'bar' },
    configurableFields: [],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },

  // ============================================================================
  // INVENTORY WIDGETS
  // ============================================================================
  {
    key: 'inventory-low-stock',
    name: 'Low Stock Items',
    description: 'Items below minimum stock threshold',
    type: 'table',
    icon: 'AlertTriangle',
    defaultWidth: 6,
    defaultHeight: 350,
    requiredPermission: 'inventory.view_stock',
    applicableRoles: ['inventory_manager', 'warehouse_manager'],
    applicableModules: ['Inventory'],
    defaultConfig: { columns: ['part_name', 'current_stock', 'minimum_level', 'reorder_qty'] },
    configurableFields: ['columns', 'threshold'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: true,
  },
  {
    key: 'inventory-total-value',
    name: 'Total Inventory Value',
    description: 'Total value of all inventory on hand',
    type: 'kpi',
    icon: 'Package',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'inventory.view_stock',
    applicableRoles: ['inventory_manager', 'warehouse_manager', 'finance_manager'],
    applicableModules: ['Inventory'],
    defaultConfig: { metric: 'total_inventory_value' },
    configurableFields: [],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },
  {
    key: 'inventory-turnover',
    name: 'Turnover Rate',
    description: 'Inventory turnover ratio',
    type: 'kpi',
    icon: 'RotateCw',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'inventory.view_stock',
    applicableRoles: ['inventory_manager', 'warehouse_manager'],
    applicableModules: ['Inventory'],
    defaultConfig: { metric: 'turnover_ratio', timeRange: 'monthly' },
    configurableFields: ['timeRange'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },

  // ============================================================================
  // ANALYTICS & HEALTH WIDGETS
  // ============================================================================
  {
    key: 'analytics-customer-health',
    name: 'Customer Health Score',
    description: 'Overall health score of customer base',
    type: 'kpi',
    icon: 'Heart',
    defaultWidth: 3,
    defaultHeight: 150,
    requiredPermission: 'analytics.view_dashboards',
    applicableRoles: ['company_admin', 'customer_success_manager'],
    applicableModules: ['Analytics'],
    defaultConfig: { metric: 'average_health_score' },
    configurableFields: ['threshold'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },
  {
    key: 'analytics-churn-risk',
    name: 'Churn Risk Customers',
    description: 'Customers identified as at-risk',
    type: 'table',
    icon: 'AlertTriangle',
    defaultWidth: 12,
    defaultHeight: 350,
    requiredPermission: 'analytics.view_dashboards',
    applicableRoles: ['company_admin', 'customer_success_manager'],
    applicableModules: ['Analytics'],
    defaultConfig: { columns: ['customer_name', 'health_score', 'risk_level', 'reason'] },
    configurableFields: ['columns', 'sortBy'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: true,
  },
  {
    key: 'analytics-activity-summary',
    name: 'Activity Summary',
    description: 'Summary of key business activities',
    type: 'card',
    icon: 'Activity',
    defaultWidth: 12,
    defaultHeight: 250,
    requiredPermission: 'analytics.view_dashboards',
    applicableRoles: ['company_admin'],
    applicableModules: ['Analytics'],
    defaultConfig: {
      showMetrics: ['tickets_created', 'deals_won', 'invoices_sent', 'new_customers'],
    },
    configurableFields: ['metrics'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },
  {
    key: 'analytics-system-health',
    name: 'System Health',
    description: 'System status and monitoring',
    type: 'card',
    icon: 'Cpu',
    defaultWidth: 6,
    defaultHeight: 200,
    requiredPermission: 'admin.view_system',
    applicableRoles: ['company_admin', 'system_admin'],
    applicableModules: ['Admin'],
    defaultConfig: { showMetrics: ['uptime', 'response_time', 'error_rate', 'active_users'] },
    configurableFields: ['metrics'],
    isDraggable: true,
    isResizable: true,
    supportsRefresh: true,
    supportsDrillDown: false,
  },
];

export async function seedDashboardWidgets() {
  try {
    // Check if widgets already exist
    const existingCount = await db.query.dashboardWidgets?.findMany?.();
    if (existingCount && existingCount.length > 0) {
      log.info(`✅ Dashboard widgets already seeded (${existingCount.length} widgets)`);
      return;
    }

    // Insert all widgets
    for (const widget of dashboardWidgetDefinitions) {
      await db.insert(dashboardWidgets).values({
        key: widget.key,
        name: widget.name,
        description: widget.description,
        type: widget.type,
        icon: widget.icon,
        defaultWidth: widget.defaultWidth,
        defaultHeight: widget.defaultHeight,
        requiredPermission: widget.requiredPermission,
        applicableRoles: widget.applicableRoles as any,
        applicableModules: widget.applicableModules as any,
        defaultConfig: widget.defaultConfig as any,
        configurableFields: widget.configurableFields as any,
        isDraggable: widget.isDraggable,
        isResizable: widget.isResizable,
        supportsRefresh: widget.supportsRefresh,
        supportsDrillDown: widget.supportsDrillDown,
        isActive: true,
      });
    }

    log.info(`✅ Seeded ${dashboardWidgetDefinitions.length} dashboard widgets`);
  } catch (error) {
    log.error('Error seeding dashboard widgets:', error);
  }
}
