/**
 * Generates client/public/sitemap.xml from the public SEO route table.
 *
 * robots.txt has advertised https://printyx.net/sitemap.xml since it was
 * written and no sitemap ever existed - every crawler that followed that line
 * got the SPA shell back at 200 (Cloudflare Pages serves index.html for any
 * unmatched path), which is worse than a 404: it looks like a valid but
 * unparseable sitemap.
 *
 * The route table is the single source of truth. A path that is noindex is
 * excluded, because listing a page in a sitemap while telling crawlers not to
 * index it is a contradiction they resolve by trusting neither.
 *
 *   npm run seo:sitemap        write the file
 *   npm run check:sitemap      fail if the committed file is stale
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SITE_URL, getSitemapRoutes } from '../client/src/lib/seo/seoConfig.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'client/public/sitemap.xml');

/** XML text escaping. Slugs are kebab-case today; a future one may not be. */
function xmlEscape(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

export function buildSitemap(lastmod: string): string {
  const routes = [...getSitemapRoutes()].sort((a, b) => {
    const byPriority = (b.priority ?? 0.5) - (a.priority ?? 0.5);
    return byPriority !== 0 ? byPriority : a.path.localeCompare(b.path);
  });

  const urls = routes
    .map((route) => {
      const loc = xmlEscape(`${SITE_URL}${route.canonicalPath ?? route.path}`);
      const lines = ['  <url>', `    <loc>${loc}</loc>`, `    <lastmod>${lastmod}</lastmod>`];
      if (route.changefreq) lines.push(`    <changefreq>${route.changefreq}</changefreq>`);
      if (route.priority !== undefined)
        lines.push(`    <priority>${route.priority.toFixed(1)}</priority>`);
      lines.push('  </url>');
      return lines.join('\n');
    })
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mts from client/src/lib/seo/seoConfig.ts. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

/**
 * lastmod: the commit date of the SEO route table, not "now". Regenerating on
 * an unrelated build must not restamp every URL as freshly changed - a sitemap
 * that claims daily changes it cannot back up gets its lastmod ignored.
 */
function routeTableLastModified(): string {
  try {
    const iso = execFileSync(
      'git',
      ['log', '-1', '--format=%cs', '--', 'client/src/lib/seo/seoConfig.ts'],
      { cwd: ROOT, encoding: 'utf8' },
    ).trim();
    if (/^\d{4}-\d{2}-\d{2}$/.test(iso)) return iso;
  } catch {
    /* not a git checkout - fall through */
  }
  return new Date().toISOString().slice(0, 10);
}

const check = process.argv.includes('--check');
const generated = buildSitemap(routeTableLastModified());

if (check) {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    console.error('sitemap: client/public/sitemap.xml is missing. Run `npm run seo:sitemap`.');
    process.exit(1);
  }
  // Compare URL sets rather than bytes: lastmod moves with the route table's
  // commit date, which differs between a working tree and a fresh checkout.
  const locs = (s: string) => [...s.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]).join('\n');
  if (locs(current) !== locs(generated)) {
    console.error(
      'sitemap: client/public/sitemap.xml is stale relative to seoConfig.ts. Run `npm run seo:sitemap`.',
    );
    process.exit(1);
  }
  console.log(`sitemap: up to date (${locs(generated).split('\n').length} URLs)`);
} else {
  writeFileSync(OUT, generated, 'utf8');
  console.log(`sitemap: wrote ${OUT} (${generated.match(/<loc>/g)?.length ?? 0} URLs)`);
}
