apiVersion: v1
kind: ServiceAccount
metadata:
  name: printyx
  namespace: printyx
  labels:
    app.kubernetes.io/name: printyx
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
